import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const root = process.cwd();
const outDir = path.join(root, 'store-assets');
const sharedDir = path.join(outDir, 'shared');
const googlePlayDir = path.join(outDir, 'google-play');

function svgTextOverlay() {
  return Buffer.from(`
<svg width="1024" height="500" viewBox="0 0 1024 500" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="1024" height="500" fill="rgba(46,46,46,0.30)"/>
  <rect x="38" y="40" width="418" height="420" fill="#FFF7E8" stroke="#2D2D2D" stroke-width="8"/>
  <rect x="52" y="54" width="390" height="74" fill="#FFDA3D" stroke="#2D2D2D" stroke-width="6"/>
  <text x="247" y="101" text-anchor="middle" font-family="monospace" font-size="34" font-weight="800" fill="#2D2D2D">FLAG ARCADE</text>
  <text x="68" y="190" font-family="monospace" font-size="44" font-weight="900" fill="#16823A">RETRO FLAG</text>
  <text x="68" y="244" font-family="monospace" font-size="44" font-weight="900" fill="#16823A">QUIZ GAMES</text>
  <text x="70" y="312" font-family="monospace" font-size="24" font-weight="700" fill="#2D2D2D">197 countries.</text>
  <text x="70" y="348" font-family="monospace" font-size="24" font-weight="700" fill="#2D2D2D">Six game modes.</text>
  <text x="70" y="384" font-family="monospace" font-size="24" font-weight="700" fill="#2D2D2D">Built for quick play.</text>
  <rect x="70" y="408" width="252" height="38" fill="#2A46B8" stroke="#2D2D2D" stroke-width="4"/>
  <text x="196" y="434" text-anchor="middle" font-family="monospace" font-size="20" font-weight="900" fill="#FFFFFF">PLAY THE WORLD</text>
</svg>`);
}

async function generateGooglePlayFeatureGraphic() {
  const source = path.join(root, 'public', 'modes', 'perfect-passport.webp');
  const background = await sharp(source)
    .resize(1024, 500, { fit: 'cover' })
    .blur(10)
    .modulate({ brightness: 0.82, saturation: 1.15 })
    .png()
    .toBuffer();

  const featureArt = await sharp(source)
    .resize(506, 338, { fit: 'cover' })
    .extend({ top: 8, right: 8, bottom: 8, left: 8, background: '#2D2D2D' })
    .png()
    .toBuffer();

  const output = await sharp(background)
    .composite([
      { input: svgTextOverlay(), left: 0, top: 0 },
      { input: featureArt, left: 480, top: 74 },
    ])
    .png({ compressionLevel: 9 })
    .toBuffer();

  await writeFile(path.join(googlePlayDir, 'feature-graphic.png'), output);
}

async function writeReadme() {
  await writeFile(
    path.join(outDir, 'README.md'),
    `# Store Assets

Generated by \`npm run build:store-assets\`.

## Files

- \`google-play/feature-graphic.png\` — Google Play feature graphic, 1024x500.
- \`shared/app-icon-1024.png\` — App icon source, 1024x1024.

Screenshots still need to be captured from installed iOS and Android builds so they reflect the exact submitted app.
`,
    'utf8',
  );
}

async function main() {
  await mkdir(sharedDir, { recursive: true });
  await mkdir(googlePlayDir, { recursive: true });
  await copyFile(
    path.join(root, 'ios', 'App', 'App', 'Assets.xcassets', 'AppIcon.appiconset', 'AppIcon-512@2x.png'),
    path.join(sharedDir, 'app-icon-1024.png'),
  );
  await generateGooglePlayFeatureGraphic();
  await writeReadme();
  console.log('Generated store assets in store-assets/');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
